---

- name: Install kubeadm and update packages as required
  hosts: localhost
  connection: local
  become: true

  vars:
   - privateKey: location of private key

  roles:
   - update-pkgs
   - kubeadm

